server:
  port: 8001
spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 0ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  datasource:
    url: jdbc:mysql://localhost:3306/gerry?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
   throw-exception-if-no-handler-found: true
  #static-path-pattern: /static
  resources:
      add-mappings: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gerry.task.pojo

token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 30

storage:
  # 配置两种模式（本地、阿里云）分别是 local、aliyun
  active: aliyun
  aliyun:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: 11111
    accessKeySecret: 11111
    bucketName: jnshu
  local:
    storagePath: storage
    address: http://localhost:8080/storage