server:
  port: 8002
spring:
  rabbitmq:
    addresses: f0t1.top:5672
    username: guest
    password: zhou1990
    virtual-host: /
    connection-timeout: 15s
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5

  redis:
    host: f0t1.top
    port: 6379
    password: zhou@1990
    database: 0
    timeout: 0ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
aliyun:
  smssdk:
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    accessKeyId: LTAI4FvNF4k2KFUNZV8F6ih1
    accessKeySecret: IXhk77Y4oHAWk0951Wl79EtUGWYMV2
    signName: IT修真院
    templateCode: SMS_175240801
    defaultConnectTimeout: 10000
    defaultReadTimeout: 10000
    expireTime: 5
  emailsdk:
    accountName: jnshu
    fromAlias: IT修真院
    tagName: jnshu