server:
  port: 8003
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password:
    virtual-host: /
    connection-timeout: 15s
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5

  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 0ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
dubbo:
  application:
    name: service-provider
  registry:
    address: zookeeper://localhost:2181
  protocol:
    port: -1
    name: dubbo
  provider:
    timeout: 1000
    UserRpcService:
      version: 1.0.0

aliyun:
  smssdk:
    product: Dysmsapi
    domain: dysmsapi.aliyuncs.com
    accessKeyId: LTAI4FvNF4k2KFUNZV8F6ih1
    accessKeySecret: IXhk77Y4oHAWk0951Wl79EtUGWYMV2
    signName: IT修真院
    templateCode: SMS_175240801
    defaultConnectTimeout: 10000
    defaultReadTimeout: 10000
    expireTime: 5
  emailsdk:
    accountName: jnshu
    fromAlias: IT修真院
    tagName: jnshu